---
- block:

  - name: get uptime before reboot via ssh
    raw: 'awk -F. "{ print \$1 }" /proc/uptime'
    register: uptime_before

  - name: Restart server
    shell: /usr/bin/nohup /bin/sh -c "/bin/sleep 2 && /sbin/shutdown -r now 'Reboot triggered by Ansible'" &
    become: true
    register: restart_server
    async: 0
    poll:  0
    ignore_errors: true

  - name: change reboot delay for physical server
    set_fact: reboot_delay={{ physical_reboot_delay }}
    changed_when: false
    when: ansible_product_name not in virtual_product_names

  - name: change reboot delay for physical server
    set_fact: max_reboot_time={{ physical_max_reboot_time }}
    changed_when: false
    when: ansible_product_name not in virtual_product_names

  - name: Wait for server to come back
    local_action: wait_for host={{ inventory_hostname }} port=22 delay={{ reboot_delay }} timeout={{ max_reboot_time }}
    when: restart_server.rc == 0

  - name: Wait for sshd to start servicing requests
    local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 timeout=30
    when: restart_server.rc == 0

  - name: get uptime after reboot via ssh
    raw: 'awk -F. "{ print \$1 }" /proc/uptime'
    register: uptime_after

  - name: fail unless uptime before the reboot is greater than uptime after
    fail: msg="server failed to reboot uptime before={{ uptime_before.stdout_lines[-1]}} <= after={{ uptime_after.stdout_lines[-1]}}"
    when: uptime_before.stdout_lines[-1] | int <= uptime_after.stdout_lines[-1] | int
