---
- name: Install redhat insights client and register with satellite server.
  hosts:  "{{ override_hosts | default('GC_SERVERS') }}"
  #hosts: 127.0.0.1
  #connection: local
  user: svc-ansible
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true
 
  environment:
    PATH: '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'

  tasks:
    - name: Install redhat insights client
      yum: 
        name: "{{ item }}"
        state: present
      with_items: 
        - python-requests
        - insights-client
      #when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

    - name: Register with satellite server
      command: insights-client --register 
      tags: register
      #when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
...
