---
- name: Uninstall collectl.
  hosts:  "{{ override_hosts | default('GC_SERVERS') }}"
  #hosts: 127.0.0.1
  #connection: local
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true
 
  environment:
    PATH: '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'

  tasks:
    - name: Remove collectl package. 
      yum: 
        name: "{{ item }}"
        state: absent 
      with_items: 
        - collectl

    - name: Remove /var/log/collectl
      file: 
        path: /var/log/collectl
        state: absent
...
