---
- name: Update sudo priviledges for pamsvc account 
  hosts:  "{{ override_hosts | default('GC_SERVERS') }}"
  user: svc-ansible
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true
 
  environment:
    PATH: '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
 
  vars: 
    basedir: '/home/aniteshl/ansible/ansible-unix-admin'
    templates: '{{ basedir }}/templates'
 
  tasks:
    - name: Remove existing sudo rules for pamsvc account
      lineinfile: 
        path: /etc/sudoers
        regex: '^[%]pamsvc'
        state: absent
        validate: /usr/sbin/visudo -cf %s
      tags: remove_old_sudo_privs_for_pamsvc


    - name: Updating "/etc/sudoers.d/10_pamsvc" for pamsvc account.
      template:
        src: '{{ templates }}/10_pamsvc.j2'
        dest: /etc/sudoers.d/10_pamsvc
        owner: root
        group: root
        mode: 0440
        backup: yes
        validate: /usr/sbin/visudo -cf %s
      tags: update_sudoers_pamsvc

#    - name: Remove pamsvc secondary group. 
#      command: usermod -G  pamsvc pamsvc
#      tags: remove_secondary_group
...
