---
- name: Update AllowGroups membership. 
  hosts:  "{{ override_hosts | default('GC_SERVERS') }}"
  user: svc-ansible
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true
 
  environment:
    PATH: '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
 
  vars: 
    basedir: '/home/aniteshl/ansible/ansible-unix-admin'
    templates: '{{ basedir }}/templates'
 
  tasks:
## This command is not indempotemt.
    - name: Update the sshd configuration file
      replace:
        path:  /etc/ssh/sshd_config
        regexp: 'AllowGroups usa'
        replace: 'AllowGroups usa pamsvc'
        backup: yes
      tags: update_ssh_sshd

    - name: Update the /etc/security/access.conf
      replace:
        path:  /etc/security/access.conf
        regexp: '-:ALL EXCEPT root usa'
        replace: '-:ALL EXCEPT root usa pamsvc'
        backup: yes
      tags: update_access

    - name: restart sshd service
      service: name=sshd state=restarted
      become: true
      tags: restart_sshd

    - name: Determine members of the AllowGroups
      shell: "grep AllowGroups /etc/ssh/sshd_config"
      register: result
      ignore_errors: true

    - name: Display sshd content.
      debug:
        msg: "System {{ ansible_fqdn}} has the following AllowGroups members, {{ result.stdout_lines }}."
      ignore_errors: true

    - name: Reset pam_tall2 for the pamsvc
      command: pam_tally2 -u pamsvc -r
      tags: reset_pamsvc
...
