---
- name: Decommission a GC linux server.
  hosts:  "{{ override_hosts | default('all') }}"
  become_method: sudo
  become_user: root
  become: true
  gather_facts: true

  #environment:
    #PATH: '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'

  roles:
    - { role: linux_decommission }
...
